title: Glen Stevens
author: Glen Stevens

description: >
  My name is Glen Stevens and I am a robotics Engineer who graduated from ASU 
  with my Bachelors in Robotics Engineering in 2024. I am currently working 
  on my Masters in Engineering at ASU with an expected graduation of May 2025.

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
minima:
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/glencstevens" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages
header_pages:
  - projects.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: false

